version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "gomod"
    directory: "/function-images/tests/chained-function-serving"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/function-images/tests/chained-function-eventing"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/utils/benchmarking/eventing"
    schedule:
      interval: "weekly"
updates:
  - package-ecosystem: "gomod"
    directory: "/utils/tracing/go"
    schedule:
      interval: "weekly"
