version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: “gomod”
    directory: “/function-images/tests/chained-function-serving”
    schedule:
      interval: “weekly”