version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/misc"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gomod"
    directory: "/taps"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gomod"
    directory: "/ctriface"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gomod"
    directory: "/cri"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
