dist: bionic
language: go

sudo: required

go:
  - 1.14.x
  - 1.13.x

env:
  - GO111MODULE=on

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.25.0

script:
  - go build ./... 
  - golangci-lint run ./...
  - sudo -E env "PATH=$PATH" go test -v github.com/ustiugov/fccd-orchestrator/misc
  - sudo -E env "PATH=$PATH" go test -v github.com/ustiugov/fccd-orchestrator/metrics
  - sudo -E env "PATH=$PATH" go test -v github.com/ustiugov/fccd-orchestrator/taps
  - sudo -E env "PATH=$PATH" go test -v github.com/ustiugov/fccd-orchestrator/memory/manager
