dist: bionic
language: go

go:
#  - 1.14.x
  - 1.13.x

env:
  - GO111MODULE=on

#install:
#  - make deps

script:
  - go build ./... 
  - go test -v github.com/ustiugov/fccd-orchestrator/misc
#  # "make" must be happening before "make lint" to download dependencies
#  - make
#  - make lint
#  - make test
