apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: helloworld # The name of the app
  namespace: default # The namespace the app will use
spec:
  template:
    spec:
      containers:
        - image: crccheck/hello-world:latest # Reference to the image of the app
          ports:
            - name: h2c
              containerPort: 50051
          env:
            - name: GUEST_PORT # The environment variable printed out by the sample app
              value: "50051"
            - name: GUEST_IMAGE
              value: "ustiugov/helloworld:var_workload"
