apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-repo-pv
  labels:
    usage: registry
spec:
  capacity:
    storage: 5Gi # TODO: size
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/repository
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-repo-pvc
  namespace: registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # TODO: change size?
  selector:
    matchLabels:
      usage: registry