name: stock Containerd CRI tests

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
    - 'function-images/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
    - 'function-images/**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  GOOS: linux
  GO111MODULE: on
  TMPDIR: /root/tmp/
  KUBECONFIG: /etc/kubernetes/admin.conf

jobs:
  stock-containerd-test:
    name: Stock Containerd test
    runs-on: [stock-knative]

    steps:
      - name: Setup TMPDIR
        run: mkdir -p $TMPDIR

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Fix namespace
        run: kubectl config set-context --current --namespace=default

      - name: Create helloworld container
        run: kn service create helloworld-go --image gcr.io/knative-samples/helloworld-go --env TARGET="vHive CRI test"

      - name: Invoke the deployed function
        run: |
          set -x

          export NODEPORT=$(kubectl get svc kourier-ingress -n kourier-system -o=jsonpath='{.spec.ports[0].nodePort}')
          export URL=$(kubectl get ksvc -n default helloworld-go -o jsonpath='{.status.url}')

          curl $URL:$NODEPORT

      - name: Cleaning
        if: ${{ always() }}
        run: kn service delete helloworld-go --wait
