name: MinIO tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  GOOS: linux
  GO111MODULE: on
  TMPDIR: /root/tmp/
  GOCACHE: /root/tmp/gocache
  GOPATH: /root/tmp/gopath
  GOROOT: $HOME/go

jobs:
  minio-test:
    name: Minio test
    runs-on: [self-hosted, cri]

    steps:
    - name: Setup TMPDIR
      run: mkdir -p $TMPDIR

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup firecracker-containerd
      run: ./scripts/setup_firecracker_containerd.sh

    - name: Build
      run: go build

    - name: Start vHive cluster
      run: ./scripts/cloudlab/start_onenode_vhive_cluster.sh

    - name: modify $PATH
      run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Setup minio
      run: sleep 1m && make -C ./function-images/tests/save_load_minio local

    - name: Test minio
      env:
        KUBECONFIG: /etc/kubernetes/admin.conf
      run: ./function-images/tests/save_load_minio/scripts/run_minio_k8s.sh
    
    - name: Archive log artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: ctrd-logs
        path: |
          /tmp/ctrd-logs/${{ github.run_id }}

    - name: Cleaning
      if: ${{ always() }}
      run: |
        make -C ./function-images/tests/save_load_minio clean
        ./scripts/github_runner/clean_cri_runner.sh
