name: vHive CRI tests

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
  workflow_dispatch:

env:
  GOOS: linux
  GO111MODULE: on
  TMPDIR: /root/tmp/
  GOCACHE: /root/tmp/gocache
  GOPATH: /root/tmp/gopath

jobs:
  cri-tests:
    name: CRI tests
    env:
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_VHIVE_ARGS: "-dbg"
    runs-on: [self-hosted, cri]

    steps:

    - name: Host Info
      run: |
        echo $HOSTNAME
        echo $GITHUB_RUN_ID

    - name: Setup TMPDIR
      run: mkdir -p $TMPDIR

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup firecracker-containerd
      run: ./scripts/setup_firecracker_containerd.sh

    - name: Build
      run: go build

    - name: Run vHive CRI tests
      run: make test-cri

    - name: Archive log artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: ctrd-logs
        path: |
          /tmp/ctrd-logs/${{ github.run_id }}

    - name: Cleaning
      if: ${{ always() }}
      run: ./scripts/github_runner/clean_cri_runner.sh
