name: MinIO tests

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
  workflow_dispatch:

env:
  GOOS: linux
  GO111MODULE: on

jobs:
  minio-test:
    name: Minio test
    runs-on: [self-hosted, cri]

    steps:
    - name: Setup TMPDIR
      run: mkdir -p $HOME/tmp

    - name: Set up Go 1.15
      env:
          GOROOT: $HOME/go
          GOCACHE: /root/tmp/gocache
          GOPATH: /root/tmp/gopath
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup firecracker-containerd
      run: ./scripts/setup_firecracker_containerd.sh

    - name: Build
      env:
          GOCACHE: /root/tmp/gocache
          GOPATH: /root/tmp/gopath
      run: go build

    - name: Start Containerd
      run: sudo containerd &

    - name: Start Firecracker-containerd
      run: sleep 1s && sudo /usr/local/bin/firecracker-containerd --config /etc/firecracker-containerd/config.toml &

    - name: Start vHive
      run: sleep 1s && sudo ./vhive &
      
    - name: Create k8s cluster
      run: sleep 1s && ./scripts/cluster/create_one_node_cluster.sh

    - name: modify $PATH
      env:
          GOCACHE: /root/tmp/gocache
          GOPATH: /root/tmp/gopath
      run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Setup minio
      env:
          GOCACHE: /root/tmp/gocache
          GOPATH: /root/tmp/gopath
      run: sleep 1m && make -C ./function-images/tests/save_load_minio local

    - name: Test minio
      env:
        KUBECONFIG: /etc/kubernetes/admin.conf
      run: ./function-images/tests/save_load_minio/scripts/run_minio_k8s.sh
    
    - name: Cleaning
      if: ${{ always() }}
      run: |
        make -C ./function-images/tests/save_load_minio clean
        ./scripts/github_runner/clean_cri_runner.sh