name: vHive integration tests

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
    - 'function-images/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
    - 'function-images/**'
  workflow_dispatch:

env:
  GOOS: linux
  GO111MODULE: on

jobs:
  integration-tests:
    name: Integration tests
    runs-on: [self-hosted , integ]
    strategy:
      fail-fast: false
      matrix:
        test-name: [test, test-man-bench]
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Upgrade git
      run: |
        sudo add-apt-repository ppa:git-core/ppa -y
        sudo apt update
        sudo apt install git -y

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        lfs: true
    
    - name: Pull binaries
      run: ./scripts/setup_firecracker_containerd.sh

    - name: Build
      run: go build -race -v -a ./...

    - name: Run vHive end-to-end tests
      run: make ${{ matrix.test-name }}

    - name: Archive log artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: ctrd-logs
        path: |
          /tmp/ctrd-logs/
          
    - name: Cleaning
      if: ${{ always() }}
      run: ./scripts/clean_fcctr.sh
