name: vHive unit tests

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
  workflow_dispatch:

env:
  GOOS: linux
  GO111MODULE: on

jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        module: [taps, misc, profile]
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup System
      run: ./scripts/setup_system.sh

    - name: Build
      run: go build -race -v -a ./...

    - name: Install PMU-Tools
    - uses: actions/github-script@v3
       with:
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/scripts/install_pmutool.sh`)
            console.log(script({github, context}))

    - name: Install linux tools package
      uses: mstksg/get-package@v1
      with:
        apt-get: linux-tools-`uname -r`

    - name: Run tests in submodules
      env:
          MODULE: ${{ matrix.module }}
      run: |
        make -C $MODULE test
        make -C $MODULE test-man
  
  firecracker-containerd-interface-test:
    name: "Unit tests: Firecracker-containerd interface"
    runs-on: [self-hosted, integ]
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -race -v -a ./...

    - name: Run tests in submodules
      run: |
        make -C ctriface test
        make -C ctriface test-man

    - name: Cleaning
      if: ${{ always() }}
      run: ./scripts/clean_fcctr.sh

  profile-test:
    name: "Unit tests: profile submodule"
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install linux tool package
      uses: mstksg/get-package@v1
      with:
        apt-get: linux-tools-`uname -r`
    
    - name: Run tests in profile
      run: make -C profile test
      